// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzjdkpnklhlkabkephsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6amRrcG5rbGhsa2Fia2VwaHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjc2MzgsImV4cCI6MjA2Mjg0MzYzOH0.df_9FpvD1fAhugSLyNNq0FDsKQ1j1oRCYa3h3w_J8hM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);